// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDTt0qxQNAxmgWkGzb1ja3-CbUmlia1Yc',
    appId: '1:185770187149:web:96bfcc9bca0c50fb2905c4',
    messagingSenderId: '185770187149',
    projectId: 'radio-f6f9d',
    authDomain: 'radio-f6f9d.firebaseapp.com',
    databaseURL: 'https://radio-f6f9d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'radio-f6f9d.appspot.com',
    measurementId: 'G-FXCXJ1S593',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbZJO5YaBqyX0zgzrbVe5alYnBLAGXe0I',
    appId: '1:185770187149:android:5e46a949ff1f1a8d2905c4',
    messagingSenderId: '185770187149',
    projectId: 'radio-f6f9d',
    databaseURL: 'https://radio-f6f9d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'radio-f6f9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZLFe_DSUUAmM0ovthnT76BHPRaABdSGs',
    appId: '1:185770187149:ios:03e496a55357d5d92905c4',
    messagingSenderId: '185770187149',
    projectId: 'radio-f6f9d',
    databaseURL: 'https://radio-f6f9d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'radio-f6f9d.appspot.com',
    iosBundleId: 'com.mjizle.radio',
  );
}
